# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MCP_Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MCP_Test
  pod 'GCDWebServer'
  pod 'KIF', :configurations => ['Debug']
end
