use_frameworks!

platform :ios, '10.0'

target 'UIdemo_Example' do
  pod 'UIdemo', :path => '../'
  pod 'LookinServer', :configurations => ['Debug']
  target 'UIdemo_Tests' do
    inherit! :search_paths

    
  end
end
