use_frameworks!

platform :ios, '10.0'

target 'UIdemo_Example' do
  
  pod 'UIdemo', :path => '../'
  pod 'LookinServer', :configurations => ['Debug']
  pod 'Masonry'
  pod 'WebViewJavascriptBridge'
  
  target 'UIdemo_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
               end
          end
   end
end
